#!/bin/bash -xe

# We want this hierarchy:
# /index.html Main page, not generated by Hugo
# /blog/ List of blog entries, generated by Hugo
# /blog/tags/ list of tags for blog entries, generated by Hugo but moved here
# /blog/feed/atom/ the atom feed so that readers don't have to be updated

# Remove unwanted files
rm -rf ./public/blog ./public/404.html

# Remove all the other rss feeds
rm -rf ./public/tags/*/rss.xml ./public/tags/rss.xml

# Replace the hostname
find public -type f -exec sed -i 's/\/\/localhost\:1313\//http:\/\/192.168.0.49\:1313\//' {} \;

# Fix the feed URLs
sed -i 's/<link>\//<link>https\:\/\/chris.iluo.net\/blog\//g' ./public/rss.xml
sed -i 's/<guid>\//<guid>https\:\/\/chris.iluo.net\/blog\//g' ./public/rss.xml

# Remove the about item from the feed, it's not really a blog entry
xmlstarlet ed -L -N w="http://www.w3.org/2005/Atom" -d "./rss/channel/item[./title = 'About']" ./public/rss.xml

# Move feed to public/blog/feed/atom
mkdir -p ./public/feed/atom/
mv ./public/rss.xml public/feed/atom/index.xml


# The "/blog/" will already be covered with the "/" entry, so remove this one
xmlstarlet ed -L --net -N sit="http://www.sitemaps.org/schemas/sitemap/0.9" -N x="http://www.w3.org/1999/xhtml" -d "./sit:urlset/sit:url[./sit:loc = '/blog/']" ./public/sitemap.xml

# Fix the sitemap.xml locations
sed -i 's/<loc>\//<loc>https\:\/\/chris.iluo.net\/blog\//g' ./public/sitemap.xml
